Clean up src, add test, add custom-data loader

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -26,10 +26,10 @@ jobs:
 
       - name: Run unit tests (pytest)
         run: |
-          if [ -d "scripts" ]; then
-            pytest scripts/ || echo "Tests failing - fix later"
+          if [ -d "tests" ]; then
+            pytest tests/ || echo "Tests failing - fix later"
           else
-            echo "No scripts folder found, skipping tests"
+            echo "No tests folder found, skipping tests"
           fi
 
       - name: Check model files
